#' @title Evaluating the average mean square errors on the left and right intevals of a given split i
#' @description For a given data  \code{f} and a given split \code{i}, the function returns vector of
#' two values of the average mean square errors on the left and righe intevals generated by this split.
#' @param f data of an n x nx matrix, where n is number of samples (rows) and nx reperesents the grid size
# in functional data interpreptation,
#' @param i an integer withen the range of the object, i.e \eqn{(1 , (nx-1))}, indecates the split.
#'
#' @return  vector of two average mean square errors (AMSE_L, AMSE_R):left and righr the spliting point, respectively
#' @export
#' @section References:
#' Nassar, H., Podgórski, K. (2019) Empirically driven orthonormal bases for functional data analysis. \emph{Preprint}.
#' Department of Statistics, Lund University.
#'
#' @seealso \code{opt_split}
#' @examples
#' n=10
#' f=rbetafda(n)
#' nx=dim(f)[2]
#' xx=vector()
#' for( i in 1:499){
#'   Q=split(f,i)
#'   xx[i]=Q[1]*i/nx+Q[2]*(nx-i)/nx
#' }
#' plot(xx)

split=function(f,i){
  if (!(is.data.frame(f) | is.matrix(f))){
    stop("The argument x is not a dataframe, matrix")
  }
  nx=dim(f)[2]    ### number of grid
  F1=f[,1:i, drop=FALSE]
  F2=f[,(i+1):nx, drop=FALSE]
  AMSE_L=amse(F1)      # average mean square error for the sub-samples until knot i
  AMSE_R=amse(F2)      # average mean square error for the sub-samples from knot i to the end
  split=c(AMSE_L,AMSE_R)
  return(split)
}



